package ClasesHospital;
// Generated 13-ene-2014 20:21:42 by Hibernate Tools 3.6.0



/**
 * Dept generated by hbm2java
 */
public class Dept  implements java.io.Serializable {


     private byte deptNo;
     private String dnombre;
     private String loc;

    public Dept() {
    }

	
    public Dept(byte deptNo) {
        this.deptNo = deptNo;
    }
    public Dept(byte deptNo, String dnombre, String loc) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
    }
   
    public byte getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(byte deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }




}


